// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb8SyQRRPp3CrP-p7S6Vil_l-xJxjvHCk',
    appId: '1:123181741849:web:9cff42124f4ff9f0127788',
    messagingSenderId: '123181741849',
    projectId: 'hackpue-6422a',
    authDomain: 'hackpue-6422a.firebaseapp.com',
    storageBucket: 'hackpue-6422a.appspot.com',
    measurementId: 'G-2QB88QYPBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOztTdtzliMbmE7lk8cDTaV4JZdbA-EL0',
    appId: '1:123181741849:android:c405fc25895a9ec3127788',
    messagingSenderId: '123181741849',
    projectId: 'hackpue-6422a',
    storageBucket: 'hackpue-6422a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtlMHrkqtLlfVKCiz4MD_4YK7TdrjC9U8',
    appId: '1:123181741849:ios:bbb3eea842c886fc127788',
    messagingSenderId: '123181741849',
    projectId: 'hackpue-6422a',
    storageBucket: 'hackpue-6422a.appspot.com',
    iosBundleId: 'com.example.hackpue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtlMHrkqtLlfVKCiz4MD_4YK7TdrjC9U8',
    appId: '1:123181741849:ios:bbb3eea842c886fc127788',
    messagingSenderId: '123181741849',
    projectId: 'hackpue-6422a',
    storageBucket: 'hackpue-6422a.appspot.com',
    iosBundleId: 'com.example.hackpue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb8SyQRRPp3CrP-p7S6Vil_l-xJxjvHCk',
    appId: '1:123181741849:web:54e4d72d13de5326127788',
    messagingSenderId: '123181741849',
    projectId: 'hackpue-6422a',
    authDomain: 'hackpue-6422a.firebaseapp.com',
    storageBucket: 'hackpue-6422a.appspot.com',
    measurementId: 'G-SFDGB5G9EG',
  );
}
